#!/bin/bash

# Find a directory ...
if [ -n "$CODA_SITE_LOCAL_PATH" ]; then
	cd "$CODA_SITE_LOCAL_PATH"

	if [ "true" = "$(git rev-parse --is-inside-work-tree 2>/dev/null)" ]; then
		[[ -f `which growlnotify` ]] && growlnotify -a Coda -n Coda -m "I'm going to go ahead and ignore that last request." -t "Site is already a Git repo"
		osascript -e "beep 1"
	else
		git init && ( [[ -n $(ls) ]] || touch .gitignore ) && git add .
		/usr/local/bin/gitx --commit
	fi
else
	[[ -f `which growlnotify` ]] && growlnotify -a Coda -n Coda -m "You must run this command from an active site." -t "Unable to initialize repo"
	osascript -e "beep 1"
fi

### Save this for later ... it's crashing Coda right now, but this is how you get the right path from the file browser:
# osascript -e 'tell front document of application "Coda" to return the browser local path'