#!/bin/bash

# Find a directory ...
if [ -n "$CODA_SITE_LOCAL_PATH" ]; then
	cd "$CODA_SITE_LOCAL_PATH"
elif [ -n "$CODA_FILEPATH" ]; then
	cd `dirname "$CODA_FILEPATH"`
fi

if [ "true" = "$(git rev-parse --is-inside-work-tree 2>/dev/null)" ]; then
	# Open gitx in file history mode.
	if [ -f "$CODA_FILEPATH" ]; then
		/usr/local/bin/gitx -- "$CODA_FILEPATH"
	else
		[[ -f `which growlnotify` ]] && growlnotify -a Coda -n Coda -m "Unable to locate file history." -t "Have you saved the current file?"
		osascript -e "beep 1"
	fi
else
	if [ -f "$CODA_SITE_LOCAL_PATH" ]; then
		[[ -f `which growlnotify` ]] && growlnotify -a Coda -n Coda -m "This command only works with existing Git repos." "Is this a Git repo?"
	else
		[[ -f `which growlnotify` ]] && growlnotify -a Coda -n Coda -m "Unable to locate file history." -t "Have you saved the current file?"
	fi
	osascript -e "beep 1"
fi
